// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.3
// source: api.proto

package info

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SoftwareInfoServiceClient is the client API for SoftwareInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SoftwareInfoServiceClient interface {
	GetSoftwareInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type softwareInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSoftwareInfoServiceClient(cc grpc.ClientConnInterface) SoftwareInfoServiceClient {
	return &softwareInfoServiceClient{cc}
}

func (c *softwareInfoServiceClient) GetSoftwareInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/software.SoftwareInfoService/GetSoftwareInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoftwareInfoServiceServer is the server API for SoftwareInfoService service.
// All implementations must embed UnimplementedSoftwareInfoServiceServer
// for forward compatibility
type SoftwareInfoServiceServer interface {
	GetSoftwareInfo(context.Context, *InfoRequest) (*InfoResponse, error)
	mustEmbedUnimplementedSoftwareInfoServiceServer()
}

// UnimplementedSoftwareInfoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSoftwareInfoServiceServer struct {
}

func (UnimplementedSoftwareInfoServiceServer) GetSoftwareInfo(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSoftwareInfo not implemented")
}
func (UnimplementedSoftwareInfoServiceServer) mustEmbedUnimplementedSoftwareInfoServiceServer() {}

// UnsafeSoftwareInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoftwareInfoServiceServer will
// result in compilation errors.
type UnsafeSoftwareInfoServiceServer interface {
	mustEmbedUnimplementedSoftwareInfoServiceServer()
}

func RegisterSoftwareInfoServiceServer(s grpc.ServiceRegistrar, srv SoftwareInfoServiceServer) {
	s.RegisterService(&SoftwareInfoService_ServiceDesc, srv)
}

func _SoftwareInfoService_GetSoftwareInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftwareInfoServiceServer).GetSoftwareInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/software.SoftwareInfoService/GetSoftwareInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftwareInfoServiceServer).GetSoftwareInfo(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SoftwareInfoService_ServiceDesc is the grpc.ServiceDesc for SoftwareInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SoftwareInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "software.SoftwareInfoService",
	HandlerType: (*SoftwareInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSoftwareInfo",
			Handler:    _SoftwareInfoService_GetSoftwareInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
