scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "polypully-openai-checker"
    static_configs:
      - targets: ["host.docker.internal:9091"]
